name: Documentation Generation
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docgen:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM 21 from Homebrew
        if: matrix.os == 'macos-26'
        run: |
          brew install llvm@21
          echo "CC=/opt/homebrew/opt/llvm@21/bin/clang" >> $GITHUB_ENV
          echo "CXX=/opt/homebrew/opt/llvm@21/bin/clang++" >> $GITHUB_ENV
      - run: cd oclint-scripts && ./gh-actions docgen
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        if: github.event_name == 'push'
      - name: Copy artifacts to AWS S3
        env:
          RUNNER_OS: ${{ matrix.os }}
        run: aws s3 cp build/ s3://travisci-artifacts.oclint.org/${GITHUB_REPOSITORY}/gh-docgen-${GITHUB_RUN_ID}/${RUNNER_OS} --recursive --exclude "*" --include "oclint-*.tar.gz"
        if: github.event_name == 'push'
